#!/usr/bin/env bash

log() {
  echo "$@"
}

run() {
	docker-compose up -d
}

stop() {
    docker-compose stop
}

stat() {
    docker-compose ps
}

restart() {
    stop
    run
}

build() {
    docker-compose build
}

terminal() {
    docker-compose exec --user dockuser $1 zsh
}
t() {
    docker-compose exec --user dockuser $1 zsh
}

$*
